### PR TITLE
Update README.md

### LINKED ISSUE #37: Automatic embedment and updation of Contributors table
As of now the Contributors table on the readme.md file is not up to date . Also one needs to update it manually each and every time. I wanna automate this task by adding a contributors table which will update automatically. 
Moreover, I wanna add a separate line to showcase the project admin if you want.

### LINKED ISSUE #40: Added all contributers name and project admin name in the README.md and upadte README.md and also add strangers graph
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**]
screenshot-github com-2021 02 07-22_11_43

### PR DESCRIPTION
**Pull request by Swastik1710**
This would close issue #37 
Added a separate line to showcase project admin.
Added a new Contributors table which gets updated automatically.

Before 
Prev

After 
Readme

### CODE REVIEW

**Comment by Swastik1710** [comment]
Hey @IIITM-Jay , I dunno why but this Greetings check failed due to some reason. Please have a look.

**Comment by IIITM-Jay** [comment]
@Swastik1710 Swastik this kind of display is already showing on the repository on  the right hand side of the curent repo, the only difference is that you are making with the project admin column. Can you try displaying the same ,one which you uplaoded as a *Before* tag image with an automatic version. This will look good when the already displaying contributing members is displayed with an automation feature... :hugs: :+1:

**Comment by IIITM-Jay** [comment]
Swastik @Swastik1710 i.e., the format of displaying must remain same , the only difference you want to make is the incorporation of automatic feature.

**Comment by IIITM-Jay** [comment]
@Swastik1710 Swastik have you done any updates :thinking: ?

**Comment by Swastik1710** [comment]
Hey @IIITM-Jay 
Please add the bot to the repo and test it out.
And kindly accept this PR too.
I've added a line which represents the Project Admin separately.

**Comment by Swastik1710** [comment]
@IIITM-Jay,
Have u added the bot?

**Comment by IIITM-Jay** [comment]
@all-contributors please add @Swastik1710 for doc

**Pull request merged**
